version: "3.8"

services:
  printbed:
    container_name: printbed
    image: prosthetichead/printbed:latest
    user: "${PUID}:${PGID}"
    volumes:
      - ${DOCKERCONFDIR}/printbed/dbdata:/appdata
      - ${DOCKERCONFDIR}/printbed/print-files:/print-files
    ports:
      - 4040:8080
    restart: unless-stopped
    networks:
      - generalStackNetwork
    labels:
      - docker-volume-backup.stop-during-backup=true

networks:
  generalStackNetwork:
    driver: bridge
    external: true
