version: '3'
services:
  actual_server:
    image: actualbudget/actual-server:latest
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    volumes:
      - ${DOCKERCONFDIR}/actual-budget:/data
    restart: unless-stopped
    ports:
      - '5006:5006'
    networks:
      - generalStackNetwork

networks:
  generalStackNetwork:
    driver: bridge
    external: true