x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - managementStackNetwork
    - socketProxyNetwork

x-logging-conf: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "2"
      max-size: "100m"

x-authentik-conf: &labels
  labels:
    - docker-volume-backup.stop-during-backup=true

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}
  DOCKER_HOST: dockerproxy

services:
  ## DOCKER VOLUME BACKUP ##
  docker-volume-backup:
    image: offen/docker-volume-backup:latest
    container_name: docker-volume-backup
    environment:
      BACKUP_CRON_EXPRESSION: "30 05 * * *"
      BACKUP_COMPRESSION: "gz"
      GZIP_PARALLELISM: 1
      BACKUP_FILENAME: backup-rd450-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_SKIP_BACKENDS_FROM_PRUNE: s3,webdav,ssh,azure,dropbox
      BACKUP_ARCHIVE: "/archive"
      BACKUP_RETENTION_DAYS: "7"
      BACKUP_PRUNING_LEEWAY: "1m"
      BACKUP_PRUNING_PREFIX: "backup-rd450"
      EXEC_FORWARD_OUTPUT: "false"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"
    networks:
      - managementStackNetwork
    volumes:
      - ${DOCKERCONFDIR}:/backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /smb/backups/dockerBackups:/archive:rw

  # zerobyte:
  #   image: ghcr.io/nicotsx/zerobyte:v0.39
  #   container_name: zerobyte
  #   restart: unless-stopped
  #   cap_add:
  #     - SYS_ADMIN
  #   ports:
  #     - "4096:4096"
  #   devices:
  #     - /dev/fuse:/dev/fuse
  #   networks:
  #     - managementStackNetwork
  #   environment:
  #     TZ: ${TZ}
  #     BASE_URL: http://192.168.1.6:4096
  #     APP_SECRET: ${ZEROBYTE_APP_SECRET}
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /var/lib/zerobyte:/var/lib/zerobyte
  #     - ${DOCKERCONFDIR}:/backup:ro
  #     - /smb/backups/dockerBackups:/smb_share

networks:
  managementStackNetwork:
    driver: bridge
    external: true