x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    environment:
      <<: *environment
    restart: unless-stopped
    networks:
      - managementStackNetwork
      - generalStackNetwork
      - socketProxyNetwork
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"
    ports:
      - 4443:443
      - 880:80
      - 881:81
    volumes:
      - ${DOCKERCONFDIR}/nginx-proxy-manager/data:/data
      - ${DOCKERCONFDIR}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt


networks:
  managementStackNetwork:
    driver: bridge
    external: true
  generalStackNetwork:
    driver: bridge
    external: true
  socketProxyNetwork:
    driver: bridge
    external: true
