services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    ports:
      - 3045:3000
    volumes:
      - ./config/docker.yaml:/app/config/docker.yaml
      - ./config/services.yaml:/app/config/services.yaml 
      - ${DOCKERCONFDIR}/homepage/config:/app/config 
    networks:
      - generalStackNetwork
      - socketProxyNetwork
    labels:
      - docker-volume-backup.stop-during-backup=true

networks:
  generalStackNetwork:
    driver: bridge
    external: true
  socketProxyNetwork:
    driver: bridge
    external: true
