version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    user: "${PUID}:${PGID}"
    environment:
      TZ: ${TZ}
    volumes:
      - ${DOCKERCONFDIR}/prometheus/config:/etc/prometheus
      - ${DOCKERCONFDIR}/prometheus/data:/prometheus
    command: "--config.file=/etc/prometheus//prometheus.yml"
    restart: unless-stopped
    labels:
      - swag=enable
      - swag_auth=authelia
    networks:
      - shyDockerServer

networks:
  shyDockerServer:
    driver: bridge
    external: true
