version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    user: "${PUID}:${PGID}"
    ports:
      - "3000:3000"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    volumes:
      - ${DOCKERCONFDIR}/grafana:/var/lib/grafana
    restart: unless-stopped
    labels:
      - swag=enable
      - swag_auth=authelia
    networks:
      - shyDockerServer

networks:
  shyDockerServer:
    driver: bridge
    external: true
