title: One sky, one destiny.

theme: dark
color: slate

providers:
  openweathermap: "{{HOMEPAGE_VAR_OPEN_WEATHER_MAP_API_KEY}}"

statusStyle: "dot"
headerStyle: boxed
language: en
target: _blank # open links in a new tab
background: 
  image: /images/vanitas.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: duckduckgo

layout:
  Important stuff:
    tab: Important
    style: row
    columns: 2
  HP SFF Monitoring:
    tab: Important
    useEqualHeights: true
    style: row
    columns: 3
    header: false
  T440p_1 Monitoring:
    tab: Important
    useEqualHeights: true
    style: row
    columns: 3
    header: false
  RD450 Monitoring:
    tab: Important
    useEqualHeights: true
    style: row
    columns: 3
    header: false
  Management:
    tab: Management
    style: row
    columns: 3
    header: false
  General:
    tab: General
    style: row
    columns: 3
    header: false
  Media:
    tab: Media
    style: row
    columns: 3
    header: false