services:
  slskd:
    container_name: slskd
    image: slskd/slskd:latest
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - "SLSKD_SHARED_DIR=/music"
    ports:
      - 5031:5031/tcp
      - 50300:50300/tcp
    networks:
      - generalStackNetwork
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"
    labels:
      - docker-volume-backup.stop-during-backup=true
    volumes:
      - ${DOCKERCONFDIR}/slskd:/app:rw
      - ${DOCKERSTORAGEDIR}/downloads/slskd:/app/downloads:rw
      - ${DOCKERSTORAGEDIR}/medialibrary/music:/music:rw


networks:
  generalStackNetwork:
    driver: bridge
    external: true
