version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - generalStackNetwork

x-authelia-conf: &authelia
  labels:
    - swag=enable
    - swag_auth=authelia

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    container_name: ryot
    environment:
      <<: *environment
      SERVER_INSECURE_COOKIE: false
      POSTGRES_PASSWORD: ${RYOT_POSTGRES_PWD}
      DATABASE_URL: "ryot_postgres_db://shyonaePostgresUser:${POSTGRES_PASSWORD}@ryot_postgres_db:5432/postgres"
    <<: *default_conf
    ports:
      - "8192:8000"
    volumes:
      - ${DOCKERCONFDIR}/ryot:/data
    pull_policy: always

  ryot_postgres_db:
    image: postgres:15-alpine
    container_name: ryot_postgres_db
    environment:
      <<: *environment
      POSTGRES_PASSWORD: ${RYOT_POSTGRES_PWD}
      POSTGRES_USER: shyonaePostgresUser
      POSTGRES_DB: ryot_postgres_db
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/ryot/postgres_storage:/var/lib/postgresql/data 

networks:
  generalStackNetwork:
    driver: bridge
    external: true
