services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest-rootless
    container_name: homebox
    restart: unless-stopped
    networks:
      - generalStackNetwork
    labels:
      - docker-volume-backup.stop-during-backup=true
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      HBOX_LOG_LEVEL: info
      HBOX_LOG_FORMAT: text
      HBOX_WEB_MAX_UPLOAD_SIZE: 10
    volumes:
      - ${DOCKERCONFDIR}/homebox:/data/
    ports:
      - 3100:7745

networks:
  generalStackNetwork:
    driver: bridge
    external: true
